"""Added many to many relationships

Revision ID: 58c0db7b0b7b
Revises: 00be0b88c189
Create Date: 2023-09-06 10:08:00.108253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c0db7b0b7b'
down_revision: Union[str, None] = '00be0b88c189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_orders',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_game_orders_customer_id_customers')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_orders_game_id_games')),
    sa.PrimaryKeyConstraint('customer_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_orders')
    # ### end Alembic commands ###
